### ISSUE TITLE
Error When Editing Match

### ISSUE THREAD

**Issue by leon-rdo** [leon-rdo/FFBVI#7]
# Error When Editing Match

On the match details page, when you click on the edit button, a Bootstrap `offcanvas` opens with the edit form (an `<input type="date">` and an `<input type="time">`), When clicking the save button, the following error occurs:

```bash
2024-02-13 22:08:33,760: Internal Server Error: /partidas/5fbed5d9-69d7-4f07-92d2-d8f3c9dc20bb/
Traceback (most recent call last):
  File "/home/ffbvi/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ffbvi/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ffbvi/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ffbvi/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ffbvi/FFBVI/main/views.py", line 251, in post
    return super().post(request, *args, **kwargs)
  File "/home/ffbvi/.local/lib/python3.10/site-packages/django/views/generic/edit.py", line 151, in post
    return self.form_valid(form)
  File "/home/ffbvi/FFBVI/main/views.py", line 222, in form_valid
    partida = self.get_partida()
AttributeError: 'PartidaView' object has no attribute 'get_partida'
```

**Comment by leon-rdo** [comment]
The method `get_partida()` does not exist  on `PartidaView` anymore, it is now called `get_object()`.

**It has been fixed now.** All `get_partida()` on  `PartidaView` were changed for `get_object()`.
